
const fs = require('fs');
const path = require('path');

// --- Configuration ---
const STATE_FILE = '.neo_state';
const SPEC_FILE = 'neo.execution_spec.v1.json';
const CUBE_DB = 'cube_cells.json';

// --- Load SSoT ---
function loadJSON(filename) {
    if (!fs.existsSync(filename)) return null;
    return JSON.parse(fs.readFileSync(filename, 'utf-8'));
}

const ssotPhase = loadJSON('trinity.phase.json');
const ssotTrans = loadJSON('trinity.transitions.json');
const ssotAgents = loadJSON('trinity.agents.json');
const cubeMap = loadJSON('cube_cells.json');
const dodRules = loadJSON('neo.dod_rules.v1.json');

if (!ssotPhase || !ssotTrans || !ssotAgents || !cubeMap || !dodRules) {
    console.error("❌ Critical SSoT files missing. Run setup_neo.js.");
    process.exit(1);
}

// --- State Management ---
function getState() {
    if (fs.existsSync(STATE_FILE)) {
        const s = loadJSON(STATE_FILE);
        if (!s.history) s.history = [];
        return s;
    }
    return { phase: "CE+", history: [] };
}

function saveState(state) {
    fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));
}

// --- Evaluators ---
const Evaluators = {
    file_exists: (args) => {
        const p = args.path_or_ref;
        const exists = fs.existsSync(p);
        return { pass: exists, msg: exists ? `File exists: ${p}` : `File missing: ${p}` };
    },
    contains_sections: (args) => {
        const p = args.markdown_ref;
        if (!fs.existsSync(p)) return { pass: false, msg: `File missing: ${p}` };
        const content = fs.readFileSync(p, 'utf-8');
        const missing = args.required_headings.filter(h => !content.includes(h));
        return {
            pass: missing.length === 0,
            msg: missing.length === 0 ? `Sections ok: ${p}` : `Missing sections in ${p}: ${missing.join(', ')}`
        };
    },
    tests_pass: (args) => ({ pass: true, msg: "Mock: Tests passed" }), // Mock
    ci_green: (args) => ({ pass: true, msg: "Mock: CI Green" }), // Mock
    metric_below: (args) => ({ pass: true, msg: "Mock: Metric compliant" }),
    metric_above: (args) => ({ pass: true, msg: "Mock: Metric compliant" })
};

// --- Agent Simulator ---
function runAgent(phaseId, requiredCells) {
    const agentDef = ssotAgents.agents.find(a => a.phase === phaseId);
    if (!agentDef) return;

    console.log(`🤖 Agent [${agentDef.name}] Active... ("${agentDef.role}")`);
    console.log(`   ❝ ${agentDef.signature_quote} ❞`);
    console.log(`   Mission: ${agentDef.mission}`);

    // Simulate work: Create missing required files
    for (const req of requiredCells) {
        for (const dod of req.dod) {
            if (dod.predicate === 'file_exists') {
                const fpath = dod.args.path_or_ref;
                if (!fs.existsSync(fpath)) {
                    console.log(`   🛠  [${agentDef.name}] Generating artifact: ${fpath}`);
                    const content = `# ${req.artifact_slug}\n\nGenerated by ${agentDef.name}.\n\n## Meta\n- Phase: ${phaseId}\n- Mission: ${agentDef.mission}\n`;
                    fs.writeFileSync(fpath, content);
                }
            }
            if (dod.predicate === 'contains_sections') {
                const fpath = dod.args.markdown_ref;
                // verify exist first
                if (!fs.existsSync(fpath)) {
                    // created above
                }
                // Check if we need to append sections
                let content = fs.existsSync(fpath) ? fs.readFileSync(fpath, 'utf-8') : "";
                let changed = false;
                for (const h of dod.args.required_headings) {
                    if (!content.includes(h)) {
                        content += `\n## ${h}\n(Content for ${h})\n`;
                        changed = true;
                    }
                }
                if (changed) {
                    console.log(`   ✍️  [${agentDef.name}] Filling sections in: ${fpath}`);
                    fs.writeFileSync(fpath, content);
                }
            }
        }
    }
}

// --- Main Runner Loop ---
async function main() {
    console.clear();
    console.log("----------------------------------------------------------------");
    console.log("   🟢  N E O   R U N N E R   v 1.0   ");
    console.log("----------------------------------------------------------------");

    // 0. The Awakening (Leader Check)
    const leader = ssotAgents.agents.find(a => a.id === 'A01');
    console.log(`\n🕶️  System Leader: ${leader.name} ("${leader.role}")`);
    console.log(`   "${leader.signature_quote}"`);
    console.log("----------------------------------------------------------------");

    // 0.5 Roll Call (Brief)
    let state = getState();
    // Only show roll call if at start
    if (state.phase === 'CE+') {
        console.log("\n📋 Initializing Team...");
        ssotAgents.agents.forEach(a => {
            console.log(`   [${a.phase}] ${a.name.padEnd(14)} : ${a.role}`);
        });
        console.log("----------------------------------------------------------------");
    }

    console.log(`\n📍 Current Status: [ ${state.phase} ]`);

    // 1. Get Requirements
    const required = dodRules.required_cells_per_phase[state.phase] || [];
    if (required.length === 0) {
        console.log("No requirements defined for this phase.");
    }

    // 2. Run Agent (Automatic Work)
    runAgent(state.phase, required);

    // 3. Verify DoD
    let allDone = true;
    for (const req of required) {
        console.log(`   🔍 Verifying [${req.artifact_slug}]...`);
        for (const check of req.dod) {
            const ev = Evaluators[check.predicate];
            const res = ev ? ev(check.args) : { pass: false, msg: "Unknown predicate" };
            const icon = res.pass ? "✅" : "❌";
            console.log(`      ${icon} ${check.predicate} -> ${res.msg}`);
            if (!res.pass) allDone = false;
        }
    }

    // 4. Transition Logic
    if (allDone) {
        const trans = ssotTrans.transitions.find(t => t.from === state.phase);
        if (trans) {
            console.log(`\n🚀 Transition Event: [${trans.event}] triggered!`);
            console.log(`   Moving: ${trans.from} -> ${trans.to}`);

            // Record History
            state.history.push({
                from: state.phase,
                to: trans.to,
                ts: new Date().toISOString(),
                event: trans.event
            });

            state.phase = trans.to;
            saveState(state);

            // Special Handle: SR0 Reboot
            if (trans.from === 'SR0' && trans.to === 'CE+') {
                console.log("\n🔄 SYSTEM REBOOT INITIATED via T13...");
                // Note: We keep history but cycle back to CE+
            }

            // Auto-continue for demo purposes?
            // console.log("   (Run again to process next phase)");
        } else {
            console.log("🏁 No transition defined from here.");
        }
    } else {
        console.log("\n✋ Phase Incomplete. Agent needs more cycles.");
    }
}

main();
